# Generated by Django 3.1.4 on 2020-12-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201231_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Полный пакет', 'full'), ('Бесплатный пакет', 'free')], default='Бесплатный пакет', max_length=30),
        ),
    ]
