# Generated by Django 3.1.4 on 2021-01-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
    ]
